# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python


python:
  - 3.5
  - 3.4
  - 2.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U pip
  - pip install -U tox coveralls
  - pip install -U -r requirements.txt
  - pip install -U -r requirements-dev.txt

# command to run tests, e.g. python setup.py test
script:
  - python setup.py flake8
  # - tox -e ${TOXENV}

after_success:
  coveralls

{% if cookiecutter.use_pypi_deployment_with_travis == 'y' -%}
# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: {{ cookiecutter.pypi_username }}
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
    condition: $TOXENV == py27
{%- endif %}
